version: '3.1'

services:
  order:
      image: "queue"
      build: ./bun-react
      ports:
        - 3000:3000
      networks:
        - mainNetwork

  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mainNetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mainNetwork
  
  queue:
    image: "queue"
    build: ./go-ws
    ports:
      - 8000:8000
    networks:
      - mainNetwork

networks:
  mainNetwork: 
    driver: "bridge"
