version: '3.1'

services:
  order:
    image: "order"
    build: ./bun-react
    depends_on:
      - queue
    environment:
      - DATABASE_URL=
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - mainNetwork
  
  queue:
    image: "queue"
    build: ./go-ws
    ports:
      - 8000:8000
    networks:
      - mainNetwork

networks:
  mainNetwork: 
    driver: "bridge"
