version: '3.1'

services:
  order:
    image: "order"
    build: ./frontend
    depends_on:
      - queue
    ports:
      - 3000:3000
    networks:
      - mainNetwork
  
  queue:
    image: "queue"
    build: ./go-ws
    ports:
      - 8000:8000
    networks:
      - mainNetwork

networks:
  mainNetwork: 
    driver: "bridge"
